
[font]
normal = {family = "M+CodeLat60 NerdFont", style = "Regular"}
bold = {family = "M+CodeLat60 NerdFont", style = "Bold"}
italic = {family = "M+CodeLat60 NerdFont", style = "Italic"}
bold_italic= {family = "M+CodeLat60 NerdFont", style = "BoldItalic"}

[window]
opacity=0.90


[colors.primary]
background = "#08080b"
foreground = "#ffffff"

[colors.cursor]
cursor = "#787c99"

[colors.selection]
text = "CellForeground"
background = "#515c7e"

[colors.normal]
black = "#363b54"
red = "#f7768e"
green = "#41a6b5"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#787c99"

[colors.bright]
black = "#363b54"
red = "#f7768e"
green = "#41a6b5"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#ffffff"
